apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gateway
  namespace: cenm-ent
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: gateway
  chart:
    git: git@github.com:suvajit-sarkar/blockchain-automation-framework.git
    ref: workspace
    path: platforms/r3-corda-ent/charts/gateway
  values:
    nodeName: gateway
    metadata:
      namespace: cenm-ent
      labels:
    prefix: cenm
    image:
      initContainerName: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      gatewayContainerName: corda/enterprise-gateway:1.5.0-zulu-openjdk8u242
      imagePullSecrets: 
        - name: "regcred"
      pullPolicy: IfNotPresent
    cenmServices:
      idmanName: idman
    storage:
      name: cordaentsc
    acceptLicense: YES
    vault:
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      role: vault-role
      authPath: cordaentcenm
      serviceAccountName: vault-auth
      certSecretPrefix: kv/data/cenm
      retries: 10
      sleepTimeAfterError: 15
    config:
      volume:
        baseDir: /opt/cenm
      jarPath: bin
      configPath: etc
      pvc:
        volumeSizeGatewayEtc: 1Gi
        volumeSizeGatewayLogs: 5Gi
      pod:
        resources:
          limits: 
            memory: 2Gi
          requests: 
            memory: 2Gi
      replicas: 1
    service:
      type: ClusterIP
      port: 8080
    zoneName: zone
    zonePort: 12345
    gatewayPort: 8080
    authName: auth
    authPort: 8081
