apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: notary-2db
  namespace: cenm-ent
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: notary-2db
  chart:
    git: git@github.com:suvajit-sarkar/blockchain-automation-framework.git
    ref: workspace
    path: platforms/r3-corda-ent/charts/h2
  values:
    nodeName: notary-2
    metadata:
      namespace: cenm-ent
    replicaCount: 1
    image:
      containerName: index.docker.io/hyperledgerlabs/h2:2018
      imagePullSecret: regcred
    resources:
      limits: 512Mi
      requests: 512Mi
    storage:
      name: "cordaentsc"
      memory: 512Mi
    service:
      type: NodePort
      tcp:
        port: 9101
        targetPort: 1521
      web:
        targetPort: 81
        port: 8080
    deployment:
      annotations: {}
    pvc:
      annotations: {}
