apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: notary-1
  namespace: cenm-ent
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: notary-1
  chart:
    git: git@github.com:suvajit-sarkar/blockchain-automation-framework.git
    ref: workspace
    path: platforms/r3-corda-ent/charts/notary
  values:
    nodeName: notary-1
    metadata:
      namespace: cenm-ent
    image:
      initContainerName: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
      nodeContainerName: adopblockchaincloud0502.azurecr.io/corda/enterprise-node:4.7
      imagePullSecret: regcred
      pullPolicy: Always
      privateCertificate: true
    vault:
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      certSecretPrefix: kv/data/cenm
      serviceAccountName: vault-auth
      role: vault-role
      authPath: cordaentcenm
      retries: 30
      retryInterval: 10
    service:
      p2pPort: 10002
      sshdPort: 2222
      rpc:
        address: "0.0.0.0"
        addressPort: 10003
        admin:
          address: "localhost"
          addressPort: 10770
        standAloneBroker: false
        useSSL: false
        users:
          username: notary
          password: notaryP
    networkServices:      
      doormanURL: https://idman.rc.demo.aws.blockchaincloudpoc.com
      idmanDomain: idman.rc.demo.aws.blockchaincloudpoc.com      
      networkMapURL: https://networkmap.rc.demo.aws.blockchaincloudpoc.com
      networkMapDomain: networkmap.rc.demo.aws.blockchaincloudpoc.com
      idmanName: "idman"
      networkmapName: "networkmap"
    dataSourceProperties:
      dataSource:
        password: "notary-1-db-password"
        url: "jdbc:h2:tcp://notary-1db:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
        user: "notary-1-db-user"
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dbUrl: "notary-1db"
      dbPort: 9101
    cordapps:
      getcordapps: false

    nodeConf:
      legalName: O=Notary,OU=Notary1,L=London,C=GB
      emailAddress: dev@baf.com
      notaryPublicIP: notary-1.rc.demo.aws.blockchaincloudpoc.com
      devMode: false
      notary:
        serviceLegalName: O=Notary Service,OU=Notary1,L=London,C=GB
        validating: True
        type: cenm
      p2p:
        url: notary-1.cenm-ent
      ambassador:
        p2pPort: 15015
        external_url_suffix: rc.demo.aws.blockchaincloudpoc.com
        p2pAddress: notary-1.rc.demo.aws.blockchaincloudpoc.com:15015
      jarPath: bin
      configPath: etc
      cordaJar:
        memorySize: 1524
        unit: M
      volume:
        baseDir: /opt/corda/base
      pod:
        resources:
          limits: 2056M
          requests: 2056M
      storage:
        name: cordaentsc
        memory: 512Mi
      replicas: 1
    healthCheckNodePort: 0
    sleepTimeAfterError: 60
    sleepTime: 10
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
