apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: approve-manufacturer-allchannel-peer0supplychain1-1
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: approve-manufacturer-allchannel-peer0supplychain1-1
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-demo-fabric
        namespace: flux-demo-fabric
      chart: platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.manufacturer-net:7051
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      authpath: demo-fabricmanufacturer-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/manufacturer-net/users/admin 
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.hf.demo.aws.blockchaincloudpoc.com:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.2
      name: supplychain
      version: 1
      sequence: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
