apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: manufacturer-peer0
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  interval: 1m
  releaseName: manufacturer-peer0
  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-demo-fabric
        namespace: flux-demo-fabric
      chart: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: manufacturer-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.2
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
        
    peer:
      name: peer0
      gossippeeraddress: peer0.manufacturer-net.hf.demo.aws.blockchaincloudpoc.com:8443
      gossipexternalendpoint: peer0.manufacturer-net.hf.demo.aws.blockchaincloudpoc.com:8443
      localmspid: manufacturerMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.2
      couchdb:
        username: manufacturer-user

    storage:
      peer:
        storageclassname: manufacturersc
        storagesize: 512Mi
      couchdb:
        storageclassname: manufacturersc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      authpath: demo-fabricmanufacturer-net-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/manufacturer-net/peers/peer0.manufacturer-net
      secretambassador: secretsv2/data/crypto/peerOrganizations/manufacturer-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secretsv2/data/credentials/manufacturer-net/couchdb/manufacturer?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "haproxy"
      external_url_suffix: hf.demo.aws.blockchaincloudpoc.com

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
