apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturer-initial-registration
  annotations:
    fluxcd.io/automated: "false"
  namespace: manufacturer-ns
spec:
  releaseName: manufacturer-initial-registration
  chart:
    path: platforms/r3-corda/charts/node-initial-registration
    git: git@github.com:suvajit-sarkar/blockchain-automation-framework.git
    ref: workspace
  values:
    nodeName: manufacturer
    replicas: 1
    metadata:
      namespace: manufacturer-ns  
    image:
      containerName: index.docker.io/hyperledgerlabs/corda:4.4-linuxkit
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: doorman.supplychain-ns
      networkmapCertAlias: networkmap.supplychain-ns
    nodeConf:
      p2p:
        url: manufacturer.manufacturer-ns
        port: 10002
      ambassadorAddress: manufacturer.rc.dev2.aws.blockchaincloudpoc-develop.com:15020
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
       
      detectPublicIp: false
      database:
        transactionIsolationLevel: READ_COMMITTED
        exportHibernateJMXStatistics: false
      dbUrl: manufacturerdb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://manufacturerdb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: http://networkmap.supplychain-ns:8080
      doormanURL: http://doorman.supplychain-ns:8080
      compatibilityZoneURL:
      jarVersion: 4.4
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: manufactureroperations
          permissions: [ALL]

    volume:
      baseDir: /base/corda
    resources:
      limits: "512Mi"
      requests: "512Mi"
    
    service:
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
      rpcadmin:
        port: 10005

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      role: vault-role
      authpath: cordamanufacturer
      serviceaccountname: vault-auth
      dbsecretprefix: manufacturer/credentials/database
      rpcusersecretprefix: manufacturer/credentials/rpcusers
      tokensecretprefix: manufacturer/credentials/vaultroottoken
      keystoresecretprefix: manufacturer/credentials/keystore
      certsecretprefix: manufacturer/certs
        
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
