apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-authority-trustee-auth-job
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-authority-trustee-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: https://github.com/suvajit-sarkar/bevel.git
    ref: develop
  values:
    metadata:
      name: authority-authority-trustee-auth-job
      namespace: authority-ns
    network:
      name: baf
      kubernetes_url: https://CD6C32CA31DDEE0453A01D18520C2B04.gr7.ap-south-1.eks.amazonaws.com
    image:
      name: authority
      repository: alpine:3.9.4
    vault:
      address: http://a847f8df9028943a39845717f1dae0aa-991936310.ap-south-1.elb.amazonaws.com:8080
      identity: authority-trustee
      admin_auth_path: kubernetes-authority-admin-auth
      policy: authority-authority-trustee-ro
      policy_content: path \"/authority/data/trustees/authority-trustee/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-authority-authority-trustee-auth
    account:
      admin_service: authority-admin-vault-auth
      admin_role: rw
      service: authority-authority-trustee-vault-auth
      role: ro
