apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturer-tessera-job
  namespace: manufacturer-quo
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: manufacturer-tessera-job
  chart:
    path: platforms/quorum/charts/tessera_key_mgmt
    git: git@github.com:suvajit-sarkar/blockchain-automation-framework.git
    ref: develop
  values:
    metadata:
      name: manufacturer-tessera-job
      namespace: manufacturer-quo    
    image:      
      repository: quorumengineering/tessera:21.4.0
      pullSecret: regcred
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      authpath: quorummanufacturer
      role: vault-role
      serviceaccountname: vault-auth
      tmprefix: secret/manufacturer-quo/crypto/manufacturer/transaction
