apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: university-endorser
  annotations:
    fluxcd.io/automated: "false"
  namespace: university-ns
spec:
  releaseName: university-endorser-faber
  chart:
    path: examples/identity-app/charts/faber
    git: https://github.com/suvajit-sarkar/bevel.git
    ref: develop
  values:
    metadata:
      namespace: university-ns
      name: university-endorser
    organization:
      name: university
    image:
      pullSecret: regcred
      init:
        name: certs-init
        repository: alpine:3.9.4
      agent:
        name: university-endorser
        repository: index.docker.io/truscholar2020/aries-agents:1.12.1
    service:
      ports: 
        service: 15015
        endpoint: 15016
        webhook: 15017
      
      address: university-endorser.id.truscholar.io
      
      ledger: http://authority-webserver.id.truscholar.io:15010
      genesis: http://authority-webserver.id.truscholar.io:15010/genesis
    vault:
      address: http://a847f8df9028943a39845717f1dae0aa-991936310.ap-south-1.elb.amazonaws.com:8080
      serviceAccountName: university-university-endorser-vault-auth
      authPath: kubernetes-university-university-endorser-auth
      endorserName: university-endorser
      role: ro
    storage:
      size: 128Mi
      className: university-aws-storageclass
    proxy:
      
      provider: "ambassador"
