apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: https://github.com/suvajit-sarkar/bevel.git
    ref: develop
  values:
    metadata:
      name: authority-dtg
      namespace: authority-ns
    organization:
      name: authority
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"4si6qLHTg47nMBsKMmT2qa","role":"0","verkey":"37UV19CjZ5xQJ5wW6WJpkRLDBqYgb8S9NfFZF2ZtGPLH"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-trustee","dest":"Cp3CCrVxLxWwoCUoYr8mHB","role":"0","verkey":"7SNPxKuAZYTtcQgUgUU5L5vUdaoD8VxShPw6h2aFits8"},"metadata":{"from":"4si6qLHTg47nMBsKMmT2qa"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"9TTymwRSL8tGBzuwLUCDBx","role":"2","verkey":"5cKa5miSJf5LeGbV3p4ZTAz59m3v8RRugrqb5C27foPV"},"metadata":{"from":"Cp3CCrVxLxWwoCUoYr8mHB"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"NjXvLKYyAYNGnqs3nCJCNH","role":"2","verkey":"Cr2wJCBF4cyCFFEMACuU3ghjZByQn8nucwToCSE4rHRr"},"metadata":{"from":"Cp3CCrVxLxWwoCUoYr8mHB"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-trustee","dest":"NXRQXLqgi2f9rhTpiHdBdw","role":"0","verkey":"CjS3SpDWB5kD5HehbvcgSkiVnFFyHkmCaeL1fp4bzCnf"},"metadata":{"from":"4si6qLHTg47nMBsKMmT2qa"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-1","dest":"RrA8h2cMnRHpYpYkYh4tbk","role":"2","verkey":"EYUq3XvScJuCXrS1GAVhfwcy9WcZ5a2odjbM2Qk7BJw9"},"metadata":{"from":"NXRQXLqgi2f9rhTpiHdBdw"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-2","dest":"E7WgFF6R6VBeEmbD5zqCJW","role":"2","verkey":"89WGqVWHnhwVBLY3SevoJEm4chx4VkX7aNBDpNr7ybkD"},"metadata":{"from":"NXRQXLqgi2f9rhTpiHdBdw"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
