apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: ssh://git@github.com/suvajit-sarkar/bevel.git
    ref: develop
  values:
    metadata:
      name: authority-dtg
      namespace: authority-ns
    organization:
      name: authority
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"Uah9WLyq6htXhJLBAJc7iw","role":"0","verkey":"G2tRZnPSGvZ2nyDdEqoUbNfHjwPSBN84eXQhhaPaXsXS"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-trustee","dest":"TUwDrig5qcnB1vJoQmcAVX","role":"0","verkey":"FS8vsGKMu42rwbqi3gii2po63K2YGRAAxdfnrTLooifB"},"metadata":{"from":"Uah9WLyq6htXhJLBAJc7iw"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"9EdvmhuE2hXUChLpAfdSrF","role":"2","verkey":"5VL3925t8RjvR6kq119aspzEhC8mk3G3rfjhsRGhUPFs"},"metadata":{"from":"TUwDrig5qcnB1vJoQmcAVX"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"QcmhhtMJD1o4PkuJhZgTZW","role":"2","verkey":"Dsa9s8ekq3p5XDiwcURRUqXtpyjzLJPh2NJ1YUQSZg9t"},"metadata":{"from":"TUwDrig5qcnB1vJoQmcAVX"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-trustee","dest":"CQPp5fsaKTtYaVgZZjANd5","role":"0","verkey":"7DUwtCzCgzYV6j465Lin4jUW493RFaiBbnhqDz9PnZG5"},"metadata":{"from":"Uah9WLyq6htXhJLBAJc7iw"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-1","dest":"TnbRLL2xz8TDoLZoMXqvRr","role":"2","verkey":"Fbm9nFR9NvxYt1P6SLjZUgQELpXyMLgZSxn3M1wWDYPu"},"metadata":{"from":"CQPp5fsaKTtYaVgZZjANd5"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-2","dest":"3G9L2JgxhZTa4ZkTSh3J4H","role":"2","verkey":"2EUi2HwApu3fmqZXxrMNkdWGcQpBWNyfaeXCCertCyXV"},"metadata":{"from":"CQPp5fsaKTtYaVgZZjANd5"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
