apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-supplychain-allchannel
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-supplychain-allchannel
  chart:
    git: git@github.com:suvajit-sarkar/blockchain-automation-framework.git
    ref: workspace
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: supplychain-net
      network:
        version 2.2.2
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.supplychain-net:7051
      localmspid: supplychainMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      authpath: demo-fabricsupplychain-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/supplychain-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/supplychain-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.hf.demo.aws.blockchaincloudpoc.com:8443
    channeltx: |-
      CrcDChgKFggCGgYI7/+SlwYiCmFsbGNoYW5uZWwSmgMKlwMKCmFsbGNoYW5uZWwSNRIjCgtBcHBs
      aWNhdGlvbhIUEhIKDnN1cHBseWNoYWluTVNQEgAaDgoKQ29uc29ydGl1bRIAGtECEqUCCgtBcHBs
      aWNhdGlvbhKVAggBEhIKDnN1cHBseWNoYWluTVNQEgAaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRW
      Ml8wEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFkbWlucyIsCgtFbmRv
      cnNlbWVudBIdEhMIAxIPCgtFbmRvcnNlbWVudBACGgZBZG1pbnMiNQoUTGlmZWN5Y2xlRW5kb3Jz
      ZW1lbnQSHRITCAMSDwoLRW5kb3JzZW1lbnQQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoH
      UmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1p
      bnMaJwoKQ29uc29ydGl1bRIZEhcKFVN1cHBseUNoYWluQ29uc29ydGl1bQ==