apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-supplychain
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-supplychain
  chart:
    git: git@github.com:suvajit-sarkar/blockchain-automation-framework.git
    ref: workspace
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: supplychain-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: adopblockchaincloud0502.azurecr.io/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.supplychain-net.hf.demo.aws.blockchaincloudpoc.com:8443
      localmspid: supplychainMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      authpath: demo-fabricsupplychain-net-auth
      adminsecretprefix: secretsv2/data/crypto/peerOrganizations/supplychain-net/users/admin
      orderersecretprefix: secretsv2/data/crypto/peerOrganizations/supplychain-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.hf.demo.aws.blockchaincloudpoc.com:8443
    anchorstx: |-
      CucCChgKFggCGgYI/9HQlgYiCmFsbGNoYW5uZWwSygIKxwIKCmFsbGNoYW5uZWwSZxJlCgtBcHBs
      aWNhdGlvbhJWCAESUgoOc3VwcGx5Y2hhaW5NU1ASQBoHCgNNU1ASACILCgdXcml0ZXJzEgAiCgoG
      QWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSACILCgdSZWFkZXJzEgAazwESzAEKC0FwcGxpY2F0aW9u
      ErwBCAEStwEKDnN1cHBseWNoYWluTVNQEqQBCAEaBwoDTVNQEgAaWAoLQW5jaG9yUGVlcnMSSRI/
      Cj0KOHBlZXIwLnN1cHBseWNoYWluLW5ldC5oZi5kZW1vLmF3cy5ibG9ja2NoYWluY2xvdWRwb2Mu
      Y29tEPtBGgZBZG1pbnMiDwoLRW5kb3JzZW1lbnQSACILCgdSZWFkZXJzEgAiCwoHV3JpdGVycxIA
      IgoKBkFkbWlucxIAKgZBZG1pbnM=

